version: '3.8'
services:
  postgresql:
    image: "postgres:12.4"
    # restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: michal
      POSTGRES_PASSWORD: michal
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4:latest"
    # restart: always
    ports: 
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: michal@michal.com
      PGADMIN_DEFAULT_PASSWORD: michal
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data: